# Generated by Django 3.0.4 on 2020-04-06 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookAuthor",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=30)),
            ],
            options={"verbose_name": "Book author", "verbose_name_plural": "Book authors"},
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("isbn_13", models.CharField(max_length=15)),
                ("description", models.CharField(max_length=10000)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="books", to="meadow.BookAuthor"
                    ),
                ),
            ],
            options={"verbose_name": "Book", "verbose_name_plural": "Books"},
        ),
    ]
