# Generated by Django 3.0.4 on 2020-04-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("meadow", "0001_book_and_book_author")]

    operations = [migrations.AlterField(model_name="book", name="description", field=models.TextField())]
