# Generated by Django 3.0.5 on 2020-04-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("meadow", "0002_auto_20200419_2314")]

    operations = [migrations.AddField(model_name="book", name="isbn_10", field=models.IntegerField(default=-1))]
