# Generated by Django 3.0.5 on 2020-04-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meadow', '0004_auto_20200421_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='download_link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
