# Generated by Django 3.0.5 on 2020-04-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("meadow", "0005_auto_20200424_1239")]

    operations = [
        migrations.AlterField(model_name="book", name="isbn_10", field=models.CharField(max_length=10)),
        migrations.AlterField(model_name="book", name="isbn_13", field=models.CharField(max_length=13)),
    ]
