# Generated by Django 3.0.5 on 2020-04-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meadow', '0006_mmake_isbn_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
