# Generated by Django 3.0.5 on 2020-05-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("meadow", "0007_book_is_approved")]

    operations = [
        migrations.AlterField(model_name="book", name="isbn_10", field=models.CharField(blank=True, max_length=10)),
        migrations.AlterField(model_name="book", name="isbn_13", field=models.CharField(blank=True, max_length=13)),
    ]
